version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-217-235-87.eu-west-1.compute.amazonaws.com
            database: ddvplnfag15nqb
            schema: public
            user: bnszsfibaukbgi
            password: 43335c28c7dbdd7481ac90ac4379e65f21be4f4c19fa2485c0ae0fea359397ab
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true